from setuptools import setup

setup(name='tell',
      version='0.1',
      description='News captioning experiments',
      url='https://github.com/alasdairtran/tell',
      author='Alasdair Tran',
      author_email='alasdair.tran@anu.edu.au',
      license='MIT',
      packages=['tell'],
      install_requires=[
          'allennlp',
          'pycocoevalcap @ git+ssh://git@github.com/salaniz/pycocoevalcap@master#egg=pycocoevalcap',
          'docopt',
          'spacy',
          'schema',
          'tqdm',
          'requests',
          'beautifulsoup4',
          'langdetect',
          'pymongo',
          'joblib',
          'ptvsd',
          'nltk',
          'textstat',
          'stop_words',
          'numpy',
          'Pillow',
          'torch',
          'PyYAML',
          'torchvision',
          'overrides',
      ],
      scripts=['bin/tell'],
      zip_safe=False)
